In [1]:
import numpy as np

In [5]:
np.zeros((3, 1))

array([[0.],
       [0.],
       [0.]])

In [4]:
#This verified taichi class can call other class's function
import taichi as ti
ti.init(arch=ti.cpu)
@ti.data_oriented
class AClass:
    def __init__(self):
        self.a = ti.field(ti.f32, shape=())
        self.a[None] = 1000
    @ti.func
    def getA(self):
        return self.a[None]
    
    def setA(self, a):
        self.a[None] = a

@ti.data_oriented
class BClass:
    def __init__(self, aobj: AClass):
        self.aobj = aobj
    @ti.kernel
    def work(self):
        print("getA:", self.aobj.getA())
    
a = AClass()
b = BClass(a)
b.work()
a.setA(121)
b.work()

[Taichi] Starting on arch=x64
getA: 1000.000000
getA: 121.000000


In [3]:
import taichi as ti
import numpy as np
@ti.kernel
def test(n: ti.types.ndarray()):
    print(n.shape[0])

ti.init()
test(np.zeros((10, 10)))

[Taichi] Starting on arch=x64
10


In [10]:
import taichi as ti
ti.init(arch=ti.cpu)
a = ti.field(ti.f32, shape=())
@ti.kernel
def test(n: ti.template()):
    print(n[None])
test(a)

[Taichi] Starting on arch=x64
0.000000


In [13]:
#This verified taichi class can call other class's function
import taichi as ti
ti.init(arch=ti.cpu)
vec3 = ti.types.vector(3, float)

@ti.dataclass
class Sphere:
    center: vec3
    radius: ti.f32

    @ti.func
    def area(self):
        # a function to run in taichi scope
        return 4 * math.pi * self.radius * self.radius

    def is_zero_sized(self):
        # a python scope function
        return self.radius == 0.0
    @ti.func
    def set_center(self, center):
        self.center = center
n = 10
sphere_field = Sphere.field(shape=(n,))
@ti.kernel
def test():
    for i in range(n):
        sphere_field[i].set_center(vec3(i, i, i))
        s = sphere_field[i]
        s.set_center(vec3(i + 3, i, i))
    for i in range(n):
        print(sphere_field[i].center)
test()

[Taichi] Starting on arch=x64
[0.000000, 0.000000, 0.000000]
[1.000000, 1.000000, 1.000000]
[2.000000, 2.000000, 2.000000]
[3.000000, 3.000000, 3.000000]
[4.000000, 4.000000, 4.000000]
[5.000000, 5.000000, 5.000000]
[6.000000, 6.000000, 6.000000]
[7.000000, 7.000000, 7.000000]
[8.000000, 8.000000, 8.000000]
[9.000000, 9.000000, 9.000000]


In [8]:
#Test quick hull
%matplotlib qt
from scipy.spatial import ConvexHull, convex_hull_plot_2d
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D, art3d

rng = np.random.default_rng()
points = rng.random((30, 3))   # 30 random points in 2-D
hull = ConvexHull(points)
faces = hull.simplices
vertices = hull.points
print("neigh", hull.neighbors)

fig = plt.figure()
ax = fig.add_subplot(projection="3d")

pc = art3d.Poly3DCollection(vertices[faces], edgecolor="black")
ax.add_collection(pc)
plt.show()

neigh [[11 34  5]
 [ 9  2 22]
 [10  1 25]
 [18  4 29]
 [12  3  5]
 [ 0 30  4]
 [13 20  7]
 [31  8  6]
 [24  7 21]
 [ 1 10 32]
 [ 2  9 11]
 [ 0 14 10]
 [ 4 13 16]
 [ 6 12 17]
 [11 35 15]
 [33 17 14]
 [12 36 17]
 [13 15 16]
 [ 3 20 19]
 [23 18 21]
 [ 6 18 21]
 [ 8 19 20]
 [ 1 24 27]
 [19 26 24]
 [ 8 22 23]
 [ 2 39 27]
 [23 38 27]
 [22 25 26]
 [37 29 30]
 [ 3 28 30]
 [ 5 28 29]
 [ 7 32 33]
 [ 9 31 33]
 [15 31 32]
 [ 0 35 36]
 [14 34 36]
 [16 34 35]
 [28 38 39]
 [26 37 39]
 [25 37 38]]


In [3]:
import numpy as np
a = np.zeros((100, 3))
b = np.zeros(100)
a * b[:, None]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0

In [24]:
def generate_uniform_sample_points(sampling_density):
    phi = np.pi * (3 - np.sqrt(5))
    ret = []
    for i in range(sampling_density):
        y = 1 - 2 * (i / (sampling_density - 1))
        radius = np.sqrt(1 - y * y)
        theta = phi * i
        x = np.cos(theta) * radius
        z = np.sin(theta) * radius
        ret.append([x, y, z])
    return np.array(ret, dtype=np.float32)
ret = generate_uniform_sample_points(64)
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter(ret[:,0], ret[:,1], ret[:,2])

In [26]:
ret.shape

(64, 3)

In [7]:
import taichi as ti
ti.init(arch=ti.cpu)
@ti.kernel
def test():
    vec = ti.Vector([3.9, 2.3, 3.0, 2.9999, -3.2], ti.f32)
    print(ti.floor(vec, ti.i32))
test()

[Taichi] Starting on arch=x64
[3, 2, 3, 2, -4]


In [2]:
import taichi as ti
ti.init(arch=ti.cpu)
@ti.kernel
def test():
    for di in ti.static(range(2)):
        for dj in ti.static(range(2)):
            for dk in ti.static(range(2)):
                print(di, dj, dk)
test()

[Taichi] Starting on arch=x64
0 0 0
0 0 1
0 1 0
0 1 1
1 0 0
1 0 1
1 1 0
1 1 1


In [4]:
list[range(1)]

TypeError: 'type' object is not subscriptable